### ISSUE TITLE
Add option to ignore walls

### ISSUE THREAD

**Issue by kleine-ritter** [EndlesNights/daynightlights#1]
First of all, loved it, it's really going to help me!
Now, I have to ask if there would be a chance to add an option for the light source to ignore walls, almost like the global illumination option...

Don't know if it's possible or if it makes sense, just something I'm trying to do. Like, if it's night the global illumination is set to off and if it's day it's set to on.

**Comment by EndlesNights** [comment]
It sound as though you want a small reworking/addition of the mechanics and  interactions between of walls and light. That's not something that's within the scope of this module.

Do I know if it's possible? I'm not sure if it's possible to do via the module API, perhaps you could inquiries on the Foundry Discord or add a suggestion ticket on the Foundry Gitlab page.

Also depending on what exactly you're trying to achieve you can use the wall direction for one way line of sight walls, the Limited Perception Restriction feature from terrain walls, or a mixture of the two.

**Comment by kleine-ritter** [comment]
Thanks for your time! I'll try other your suggestions!
