### ISSUE TITLE
Copy-paste not working properly

### ISSUE THREAD

**Issue by noahzorbaugh** [EndlesNights/daynightlights#2]
When using CTrl + C to copy a light source that has been set as a Day/night dual light, it copies the light but does NOT update the X,Y coordinates of the alternate light setting.  This makes copy/pasting lights for a lot of torches quite a pain.

**Comment by EndlesNights** [comment]
I'll look into implementing a proper fix, but for now a simple stopgap that you can use is to: set the Alternative Light X/Y position as nothing before you copy it. It will then inherit it's position from the current light's position when you update it.

**Comment by EndlesNights** [comment]
Should be fixed now, X/Y coordinates for the alternate should now default as a "null" or none number value, and will use the active lights current coordinates when the light swap occurs. The null value will also not be overwritten when the light swap occurs, so you can contumely reposition the lights without having to worry about them snapping back to a different unintended positions.
